

name: CI

on:
  push: 
    branches:
      - "main"

jobs:
  Build-and-Push-Image:
    runs-on: ubuntu-latest

    name: Build and Push Image to Image registry
    env:
      REGISTRY: docker.io
    # defaults:
    #   run:
    #     shell: bash
    steps:
    - name: Generate Vars
      id: generate_vars
      run: |
        # Just Tag
        IMAGE_TAG=pr-${{ github.event.pull_request.number }}-$(echo ${{ github.event.pull_request.head.sha }} | cut -c1-8)
        # Just Image name
        IMAGE_NAME=${{ github.repository }}
        #Image ID= Name + Tag
        IMAGE_ID=$IMAGE_NAME:$IMAGE_TAG
        IMAGE_REPO=$REGISTRY/$IMAGE_ID
        echo "Image: $IMAGE_REPO"
        echo "image=$IMAGE_REPO" >>$GITHUB_OUTPUT
        echo "image_name=$IMAGE_NAME" >>$GITHUB_OUTPUT

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.0.0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.0.0
    - name: Login to DockerHub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Echo Output
      run: |
        echo "Image from Output: ${{ steps.generate_vars.outputs.image }}"
        echo "Repo from Output: ${{ steps.generate_vars.outputs.image_name }}"

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5.0.0
      with:
        context: .
        file: ./dockerfile
        pull: true
        push: true
        tags: ${{ steps.generate_vars.outputs.image }}
